### ISSUE TITLE
Noise values are *way* out of advertised [0, 1] range

### ISSUE THREAD

**Issue by lloeki** [junegunn/perlin_noise#2]
Doc says [0,1] but I've seen it reach in excess of 600.

```
require 'perlin_noise'

n2d = Perlin::Noise.new 2
-2.step(2, 0.05).map do |i|
  -2.step(2, 0.05).map do |j|
    n2d[i, j]
  end
end.flatten.select { |v| v > 1 }.count.tap { |v| puts v }
# => 1577
```

**Comment by junegunn** [comment]
Works as expected with positive coordinates.

```ruby
n2d = Perlin::Noise.new 2
0.step(4, 0.05).map do |i|
  0.step(4, 0.05).map do |j|
    n2d[i, j]
  end
end.flatten.select { |v| v > 1 }.count.tap { |v| puts v }
# => 0
```

Actually I forgot the details of the algorithm (3+ years!), but it sure looks like that negative coordinates are not supported by the implementation.

**Comment by lloeki** [comment]
I suppose a C implementation (such as [perlin](https://github.com/spooner/ruby-perlin)) will use some uint then, thus making a cast signed int "magically" work, creating an interesting "wrapping" symmetry in the resulting noise.

To implement this behaviour in pure ruby and extend the domain to support negative numbers, inserting either of the following line [here](https://github.com/junegunn/perlin_noise/blob/e1f841a638ce5f6e288593916819a5fb68e3cb1b/lib/perlin/noise.rb#L30) does the trick:

```ruby
# wrap negative integers starting from maximum Fixnum+1, which makes it logically equivalent to a theoretical ruby-land signed to unsigned cast
coords.map! { |e| e < 0 ? (2**(0.size * 8 - 2) - 1 - e) : e }
# alternatively, wrap starting at C's max uint+1, which makes it strictly equivalent to a C int to uint cast.
coords.map! { |e| e < 0 ? (2**(0.size * 8 - 1) - 1 - e) : e }
```

Demo:
```
require 'perlin_noise'

def wrap(*coords)
  coords.map! { |e| e < 0 ? (2**(0.size * 8 - 2) - 1 - e) : e }
end

n2d = Perlin::Noise.new 2
-2.step(2, 0.05).map do |i|
  -2.step(2, 0.05).map do |j|
    n2d[*wrap(i, j)]
  end
end.flatten.select { |v| v > 1 }.count.tap { |v| puts v }
# => 0
```
